Baseline token generator/validator microservice
18F/identity-idva-token-service pull request #1
Opened 2022-10-19 14:21 UTC by shumatepf

First iteration of the IDVA token microservice. Documentation on how to locally setup and test are included in the readme.

This PR does not include github actions.

2022-10-19 17:33 UTC, dzaslavskiy requested changes

2022-10-19 17:40 UTC, shumatepf commented on server/config.py
> +from lib2to3.pytree import Base
Didn't notice this. Must've been autocomplete/import when I was trying to type `BaseConfig`.

2022-10-19 17:40 UTC, shumatepf commented on server/auth/views.py
> +class RefreshAPI(MethodView):
Good point, it is more of an 'invoke' than a 'refresh'.

2022-10-19 18:53 UTC, shumatepf commented on runtime.txt
> +python-3.9.14
Dependency versions are a bit dated (more so in the requirements file), but it was required for compatibility.

2022-10-21 16:15 UTC, dzaslavskiy requested changes

2022-10-21 16:15 UTC, dzaslavskiy commented on README.md
> +  "api_key": <api_key>,
api key is in header now.

2022-10-21 16:34 UTC, shumatepf commented on README.md
> +  "api_key": <api_key>,
Fixed.

2022-10-21 17:06 UTC, dzaslavskiy approved these changes

2022-10-24 16:02 UTC, merged